### ISSUE TITLE
Division structure checklist

### ISSUE THREAD

**Issue by flashadvocate** [ClanAODDev/aod-twig-templates#1]
Building this so we know where we stand on completion

- [x] AOD Racing
- [x] ARK
- [x] Armored Warfare
- [x] Battlefield
- [x] Battlefront
- [x] Black Desert
- [x] Elite: Dangerous
- [x] Jedi Knight
- [x] Overwatch
- [x] Planetside 2
- [x] PlayerUnknown
- [x] Skyforge
- [x] Titanfall 2
- [x] Tom Clancy
- [x] War Thunder
- [x] Warframe
- [x] World of Warcraft

**Comment by flashadvocate** [comment]
I've assigned all of you so you know this exists. As of now, it looks like most of the necessary functionality exists in the parser, so you should be able to build out your division structures without too much trouble, even having some additional data you didn't have before (like platoon logos).

Once you have confidently finished your structure, mark it complete here. Otherwise, you can add a percentage of completion next to the name, so we know where you stand.

**Comment by Anvil7** [comment]
The Elite Danerous structure is done. Just need the platoons and squads to be recovered from Ark who took a fancy to them lol. It's not letting me update the OP to check us off. Maybe because I am on my phone.
